Raise a meaningful error when missing has_rich_text :method
When using the rich_text_area form helper if has_rich_text was missing
the following was shown:
```
ActionView::Template::Error (undefined method `body' for nil:NilClass):
    17:   </div>
    18:
    19:   <div class="field">
    20:     <%= form.rich_text_area :content %>
    21:   </div>
    22:
    23:   <div class="actions">
```
This commit introduces a meaningful exception to help the user identify
the cause of this error:
```
ActionView::Template::Error (can't access value, possibly missing class
method `has_rich_text :content` for Post or `:content` was misspelled):
    17:   </div>
    18:
    19:   <div class="field">
    20:     <%= form.rich_text_area :content %>
    21:   </div>
    22:
    23:   <div class="actions">
```

Fixes #19